### ISSUE TITLE
Hardware used for training

### ISSUE THREAD

**Issue by xavysp** [cimerainbow/DPED#1]
Dear authors,
 thank you for sharing us DPED. With the purpose of reproduce your result, I would like to know the details of the hardware used to train your model. Thanks.

Xavier

**Comment by cimerainbow** [comment]
All the results mentioned in the paper are trained on GPU 2080Ti. The FPS in this paper is obtained on GPU P100. GPU P100 comes from google colab platform.

**Comment by xavysp** [comment]
Thank you @cimerainbow
